### PR TITLE
Look for opencpn extensions to GPX

### PR DESCRIPTION
**Pull request by tmcw**
- Refs #128

The GPX extensions support is based on a known list of extensions, and it wasn't including this opencpn extension. This adds the OpenCPN extension namespace, which adds support for those rte extensions.

cc @jaybo

### CODE REVIEW

**Comment by jaybo** [comment]
It seems wrong that every additional private extension namespace requires an update to this library.  I'm planning to add yet another namespace since I don't control **opencpn**.  

Wouldn't it be possible to just automatically add every `xmlns` entry within the `<gpx>` tag?

**Comment by tmcw** [comment]
Yeah, good point. Latest changes look for all possible xmlns: extensions, which picks up a lot more. We've got one example in test data of usage of `gpxx` with a local xmlns:

```xml
    <extensions>
      <gpxx:TrackExtension xmlns:gpxx="http://www.garmin.com/xmlschemas/GpxExtensions/v3">
        <gpxx:DisplayColor>Transparent</gpxx:DisplayColor>
      </gpxx:TrackExtension>
    </extensions>
```

So I'm adding the gpxx URL by default to the list of detected namespaces.

Thoughts - this seems more comprehensive?

**Comment by jaybo** [comment]
Can you have multiple namespaces simultaneously active?  Like:
```
<?xml version="1.0"?>
<gpx version="1.1" creator="OpenCPN" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.topografix.com/GPX/1/1" xmlns:gpxx="http://www.garmin.com/xmlschemas/GpxExtensions/v3" xsi:schemaLocation="http://www.topografix.com/GPX/1/1 http://www.topografix.com/GPX/1/1/gpx.xsd http://www.garmin.com/xmlschemas/GpxExtensions/v3 http://www8.garmin.com/xmlschemas/GpxExtensionsv3.xsd" xmlns:opencpn="http://www.opencpn.org">
  <rte>
    <name>Around Orcas</name>
    <extensions>
       <gpxx:DisplayColor>Transparent</gpxx:DisplayColor>
       <opencpn:planned_speed>6.00</opencpn:planned_speed>
        ...
````

**Comment by tmcw** [comment]
Yes, this should handle as many namespaces as are defined in the gpx root tag.

**Comment by tmcw** [comment]
Does this seem doable for your usecase? I could merge, or release a prerelease tag if you want to try it out.

**Comment by jaybo** [comment]
Looks perfect.  I was just trying to figure out how to build it for testing, but if you could either merge or pre-release, that would be great.  A mention in the readme about supporting arbitrary namespaces might be a good idea too.  Thanks for moving on this quickly!

**Comment by tmcw** [comment]
Great, pushed 6.0.0-0 to npm, try it out!

**Comment by jaybo** [comment]
I tried it with a bunch of .gpx files and it solves all of my main issues.  Thanks!

The one remaining point is that I have a GPX file which has properties attached to route waypoints.
[DavidAltRoute.txt](https://github.com/user-attachments/files/17877476/DavidAltRoute.txt)

```
<rte>
    <name>Day 2</name>
    <desc>Through Deception Pass</desc>
    <rtept lat="48.041" lon="-122.403">
      <name>Langley</name>
      <time>2024-12-07T09:00</time>
    </rtept>
    ...
````
I don't know if this is legal or common, but would it be possible to add `coordinateProperties` to **routes** as well as **tracks**?

**Comment by tmcw** [comment]
> I don't know if this is legal or common, but would it be possible to add coordinateProperties to routes as well as tracks?

Possibly, but that'd be a matter for a different PR, feel free to open another issue.

**Pull request merged**
